//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerApp.src
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKY
    {
        public string MASV { get; set; }
        public string MAMM { get; set; }
        public Nullable<decimal> DIEMTH { get; set; }
        public Nullable<decimal> DIEMQT { get; set; }
        public Nullable<decimal> DIEMCK { get; set; }
        public Nullable<decimal> DIEMTK { get; set; }
    
        public virtual MOMON MOMON { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
