//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerApp.src
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCPHAN()
        {
            this.MOMONs = new HashSet<MOMON>();
        }
    
        public string MAHP { get; set; }
        public string TENHP { get; set; }
        public Nullable<byte> SOTC { get; set; }
        public Nullable<byte> STLT { get; set; }
        public Nullable<byte> STTH { get; set; }
        public string MADV { get; set; }
    
        public virtual DONVI DONVI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOMON> MOMONs { get; set; }
    }
}
