//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagerApp.src
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOMON()
        {
            this.DANGKies = new HashSet<DANGKY>();
        }
    
        public string MAMM { get; set; }
        public string MAHP { get; set; }
        public string MAGV { get; set; }
        public Nullable<bool> HK { get; set; }
        public Nullable<short> NAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKY> DANGKies { get; set; }
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
